# Generated by Django 5.1.3 on 2024-11-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='minimum_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
