# Generated by Django 5.1.3 on 2024-12-01 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profilesubjectminscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesubjectminscore',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_scores', to='profiles.subject'),
        ),
    ]
