# Generated by Django 5.1.3 on 2024-11-26 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='recommend_profiles',
        ),
        migrations.AddField(
            model_name='answer',
            name='recommend_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_answers', to='profiles.directiontype'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_first_question',
            field=models.BooleanField(default=False),
        ),
    ]
