# Generated by Django 5.1.3 on 2024-12-12 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profilesubjectminscore_subject_id'),
        ('questions', '0002_remove_answer_recommend_profiles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='recommend_direction',
        ),
        migrations.AddField(
            model_name='answer',
            name='recommend_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_answers', to='profiles.profile'),
        ),
    ]
